export const FETCH_USERS_DATA = "FETCH_USERS_DATA";
export const USER_LIST = "USER_LIST"
export const ADD_FAVORITE_USER = "ADD_FAVORITE_USER";
export const FAVORITE_BY_ID = "FAVORITE_BY_ID";
export const SEARCH_DATA_USER = "SEARCH_DATA_USER";
export const SEARCHED_FAVORITE_USER = "SEARCHED_FAVORITE_USER";
export const INITIAL_LOADER = "INITIAL_LOADER";
